CREATE TABLE IF NOT EXISTS Account
(
  id TEXT PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS line
(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ,
  label TEXT NOT NULL,
  value REAL NOT NULL,
  accountid TEXT NOT NULL,
  FOREIGN KEY(accountid) REFERENCES Account(id)
);